CREATE TABLE "mytable" (
  "create database gestion_hospital;" text
);

INSERT INTO "mytable" ("create database gestion_hospital;")
VALUES
('use gestion_hospital;'),
('CREATE TABLE Tipo_Consulta'),
('('),
('id_tipo INT NOT NULL'),
('descripcion VARCHAR(100) NOT NULL'),
('precio FLOAT NOT NULL'),
('CONSTRAINT PK_Tipo_Consulta PRIMARY KEY (id_tipo)'),
(');'),
('CREATE TABLE Medicos'),
('('),
('id_medico INT NOT NULL'),
('nombre_apellido VARCHAR(100) NOT NULL'),
('CONSTRAINT PK_Medicos PRIMARY KEY (id_medico)'),
(');'),
('CREATE TABLE Provincia'),
('('),
('id_provincia INT NOT NULL'),
('nombre_provincia VARCHAR(100) NOT NULL'),
('CONSTRAINT PK_Provincia PRIMARY KEY (id_provincia)'),
(');'),
('CREATE TABLE Entrada'),
('('),
('id_entrada INT NOT NULL'),
('fecha_entrada DATE NOT NULL'),
('hora VARCHAR(15) NOT NULL'),
('CONSTRAINT PK_Entrada PRIMARY KEY (id_entrada)'),
(');'),
('CREATE TABLE Salida'),
('('),
('id_salida INT NOT NULL'),
('fecha_salida DATE NOT NULL'),
('hora VARCHAR(15) NOT NULL'),
('CONSTRAINT PK_Salida PRIMARY KEY (id_salida)'),
(');'),
('CREATE TABLE Control_Horarios'),
('('),
('id_control_horarios INT NOT NULL'),
('id_entrada INT NOT NULL'),
('id_salida INT NOT NULL'),
('id_medico INT NOT NULL'),
('CONSTRAINT PK_Control_Horarios PRIMARY KEY (id_control_horarios)'),
('CONSTRAINT FK_Control_Horarios_Entrada FOREIGN KEY (id_entrada) REFERENCES Entrada(id_entrada)'),
('CONSTRAINT FK_Control_Horarios_Salida FOREIGN KEY (id_salida) REFERENCES Salida(id_salida)'),
('CONSTRAINT FK_Control_Horarios_Medicos FOREIGN KEY (id_medico) REFERENCES Medicos(id_medico)'),
('--CONSTRAINT CK_Control_Horarios_Fechas CHECK (fecha_salida IS NULL OR fecha_salida >= fecha_ingreso);'),
(');'),
('CREATE TABLE Localidad'),
('('),
('id_localidad INT NOT NULL'),
('nombre_localidad VARCHAR(100) NOT NULL'),
('id_provincia INT NOT NULL'),
('CONSTRAINT PK_Localidad PRIMARY KEY (id_localidad)'),
('CONSTRAINT FK_Localidad FOREIGN KEY (id_provincia) REFERENCES Provincia(id_provincia)'),
(');'),
('CREATE TABLE Domicilio'),
('('),
('id_domicilio INT NOT NULL'),
('calle VARCHAR(100) NOT NULL'),
('numero INT NOT NULL'),
('id_localidad INT NOT NULL'),
('CONSTRAINT PK_Domicilio PRIMARY KEY (id_domicilio)'),
('CONSTRAINT FK_Domicilio_Localidad FOREIGN KEY (id_localidad) REFERENCES Localidad(id_localidad)'),
(');'),
('CREATE TABLE Paciente'),
('('),
('dni_paciente INT NOT NULL'),
('nombre_apellido VARCHAR(100) NOT NULL'),
('fecha_nac DATE NOT NULL'),
('telefono VARCHAR(20) NOT NULL'),
('id_domicilio INT NOT NULL'),
('CONSTRAINT PK_Paciente PRIMARY KEY (dni_paciente)'),
('CONSTRAINT FK_Paciente_Domicilio FOREIGN KEY (id_domicilio) REFERENCES Domicilio(id_domicilio)'),
('CONSTRAINT UK_Paciente_Telefono UNIQUE (telefono)'),
(');'),
('CREATE TABLE Consulta_Medica'),
('('),
('id_act_medica INT NOT NULL'),
('fecha DATE NOT NULL'),
('hora VARCHAR(15) NOT NULL'),
('dni_paciente INT NOT NULL'),
('id_medico INT NOT NULL'),
('id_tipo INT NOT NULL'),
('CONSTRAINT PK_Consulta_Medica PRIMARY KEY (id_act_medica)'),
('CONSTRAINT FK_Consulta_Medica_Paciente FOREIGN KEY (dni_paciente) REFERENCES Paciente(dni_paciente)'),
('CONSTRAINT FK_Consulta_Medica_Medicos FOREIGN KEY (id_medico) REFERENCES Medicos(id_medico)'),
('CONSTRAINT FK_Consulta_Medica_Tipo FOREIGN KEY (id_tipo) REFERENCES Tipo_Consulta(id_tipo)'),
(');'),
('CREATE TABLE Informes_Desempeño'),
('('),
('id_informe INT NOT NULL'),
('calificacion INT NOT NULL'),
('comentario VARCHAR(100) NOT NULL'),
('id_medico INT NOT NULL'),
('dni_paciente INT'),
('CONSTRAINT PK_Informes_Desempeño PRIMARY KEY (id_informe)'),
('CONSTRAINT FK_Informes_Desempeño FOREIGN KEY (id_medico) REFERENCES Medicos(id_medico)'),
('CONSTRAINT FK_Informes_Desempeño_Paciente FOREIGN KEY (dni_paciente) REFERENCES Paciente(dni_paciente)'),
('CONSTRAINT CK_Informes_Desempeño_Calificacion CHECK (calificacion BETWEEN 1 AND 10)'),
(');'),
('/*---------------'),
('-- LOTE DE DATOS'),
('----------------*/'),
('INSERT INTO Tipo_Consulta (id_tipo'),
('(1'),
('(2'),
('INSERT INTO Medicos (id_medico'),
('(1'),
('(2'),
('INSERT INTO Provincia (id_provincia'),
('(1'),
('(2'),
('INSERT INTO Localidad (id_localidad'),
('(1'),
('(2'),
('INSERT INTO Domicilio (id_domicilio'),
('(1'),
('(2'),
('INSERT INTO Paciente (dni_paciente'),
('(12345678'),
('(87654321'),
('INSERT INTO Entrada (id_entrada'),
('(1'),
('(2'),
('INSERT INTO Salida (id_salida'),
('(1'),
('(2'),
('INSERT INTO Control_Horarios (id_control_horarios'),
('(1'),
('(2'),
('INSERT INTO Consulta_Medica (id_act_medica'),
('(1'),
('(2'),
('INSERT INTO Informes_Desempeño (id_informe'),
('(1'),
('(2'),
('SELECT * FROM Tipo_Consulta;'),
('SELECT * FROM Medicos;'),
('SELECT * FROM Provincia;'),
('SELECT * FROM Localidad;'),
('SELECT * FROM Domicilio;'),
('SELECT * FROM Paciente;'),
('SELECT * FROM Entrada;'),
('SELECT * FROM Salida;'),
('SELECT * FROM Control_Horarios;'),
('SELECT * FROM Consulta_Medica;'),
('SELECT * FROM Informes_Desempeño;'),
('/*----------------------------------'),
('-- LOTE DE DATOS PARA RESTRICCIONES'),
('----------------------------------*/'),
('-- Datos incorrectos en Informes_Desempeño para verificar. Esto debería fallar porque la calificación está fuera del rango permitido.'),
('INSERT INTO Informes_Desempeño (id_informe'),
('(5');
